apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.26.1-alpine
        resources:
          requests:
            memory: "200Mi"
            cpu: "300m"
          limits:
            memory: "200Mi"
            cpu: "300m"
        volumeMounts:
          - name: nginx-main-conf-file
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: nginx-main-conf-file
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
          - name: nginx-main-conf-file
            mountPath: /usr/share/nginx/html/healthy.html
            subPath: healthy.html
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthy
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
        - name: nginx-main-conf-file
          configMap:
            name: nginx-configs

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-app
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - name: nginx-port
      port: 8080
      targetPort: 80